definitions:
  main.rider:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      team:
        type: string
    type: object
info:
  contact: {}
paths:
  /riders:
    get:
      description: Responds with the list of all riders as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.rider'
            type: array
      summary: Get all riders
swagger: "2.0"
